### ISSUE TITLE
Separate voting from Pull Request Review

### ISSUE THREAD

**Issue by morxa** [robocup-logistics/rcll-rulebook#19]
I think the current workflow with voting implicitly by accepting a pull request is not ideal. I therefore propose a different solution:

* Every member of the TC can vote by adding a comment (e.g., `+1`) to the PR.
* Reviews are for checking the exact wording, spelling mistakes, etc. We would no longer require 3 reviews, but only 1.

I've started implementing a simple GitHub [votebot](https://github.com/morxa/votebot) that automatically initializes votes, count votes, and evaluates the results. A typical workflow would be:

1. Voting is initialized with `/vote init` (this could happen automatically if a PR is created)
1. Every TC member votes with `/vote +1`, `/vote 0`, `/vote -1`.
1. As soon as a majority is found, the vote will automatically be closed and the result announced.

Do you think this approach makes sense? Any feedback (both to the procedure and to the bot) is welcome.

**Comment by morxa** [comment]
I see the following issues:

* No separation of feedback about simple spelling errors and general disagreement.
* If you fix a small thing, three people again need to review.
* No way to determine a deadline (e.g., voting closes in 2 weeks)
* It's not very clear how many are in favor and how many are against a proposal.
* As far as I know, you cannot merge a PR if there is one dismissing PR.

**Comment by morxa** [comment]
> > I see the following issues:
> > 
> > * No separation between feedback about simple spelling errors and general disagreement.
> 
> But a vote is even more unspecific. Here, you can place your criticism and questions right at the line they are concerned with. I actually see this as a positive element.

That's the whole point. Currently, there is no way to vote against a proposal because you don't like the idea in general. You can only request changes, which is not useful if e.g., you think competitive orders are just a bad idea.

> 
> > * If you fix a small thing, three people again need to review.
> 
> That's actually a setting branch protection: "Dismiss stale pull request approvals when new commits are pushed". We could disable this. However, this means someone can make a change, get it reviewed and approved, then push another thing which may be controversial and then merge, possibly unnoticed. Therefore, I also see this as a positive aspect of the current system.

That's why we'd still have one review. But looking at recent proposals, many reviews generally agreed but requested some rephrasing. If we separate voting and review feedback, multiple people could work on a proposal in a PR, request changes etc., and once they think it's ready, they could request a vote.

> 
> > * No way to determine a deadline (e.g., voting closes in 2 weeks)
> 
> Here I agree, but I would implement this as a reminder. We may want to have arbiter accounts, which can then pledge a review if no one else does.
> 
> > * It's not very clear how many are in favor and how many are against a proposal.
> 
> Approve is in favor, reject is against, request changes is open discussion items. I'm unsure whether a reject immediately blocks a merge, or if it can still be overridden with 3 approvals.

There are no rejections. Currently, you cannot vote against a proposal.

> 
> > * As far as I know, you cannot merge a PR if there is one dismissing PR.
> 
> You mean if there is a missing review? That's right, only administrators can do this. I think there should be two who can do an override.

I meant a rejecting review, but they don't even exist. But even if there is one PR requesting changes, you cannot merge.

> 
> So, overall I'm not convinced that a voting scheme would be better. Rather differently, I think that would place proposal and comments further apart. So currently, I'm in favor of continuing to use the review system.

**Comment by timn** [comment]
Ok, I see your point. I mean there is a workaround by stating that you dislike the changes and not reviewing/approving. So request changes would be for "I would like to accept, but..." That's all the info we need.

I still like the review process better, where proposal, comment, and approval are closer together. But I'd like to hear more feedback. @thomerz, @vcoelen, @dka14, @chde, @MostafaGomaa, @teamsolidus?

**Comment by morxa** [comment]
I don't want to replace the review process, but I want to make more about the details rather than about the general proposal. If you disagree because of one certain aspect of a proposal, you can still comment as before, and add vote `-1`.

**Comment by morxa** [comment]
At today's TC meeting, everyone agreed on splitting voting from reviewing. I started writing up the modified workflow in the [wiki](https://github.com/robocup-logistics/rcll-rulebook/wiki/Workflow-for-rule-changes) (consider to be work in progress).

**Comment by morxa** [comment]
I added a paragraph about the [voting system](https://github.com/robocup-logistics/rcll-rulebook/wiki/Workflow-for-rule-changes#voting-system), which should reflect the general consensus at the last TC meeting.

This should clarify the whole process. Feel free to re-open if there are remaining questions.

**Comment by morxa** [comment]
Currently, the bot is not in place at all (mainly because it doesn't support a limited voting period yet), so I'm counting votes manually instead. I intend to finish the work on the bot eventually, but probably not for this year's rulebook.

> I have two more suggestions:
> 
>     * count approved reviews as +1. If you approve you should not also have to vote. That can also reduce "+1" clutter in the comments

While it removes some clutter, it makes it less obvious where the votes come from. I think it would be simpler if you still commented with "+1" to make it obvious.

> 
>     * once the first vote appears, make a comment through the bot that indicates that voting has been started. It would make it clearer that something is happening and gives confirmation the system is operational. It should also state when the vote will close.

Yes, the bot would do that.

> 
> 
> And one question: I disabled voting removing the label on #9 since it wasn't clear what we were voting on. Will this reset the timer once the label is added again (and will the bot ignore this once started voting and not post a result after the timeout)?

Yes, I will take this into account when manually checking the results, and the bot will do that, too.

**Comment by timn** [comment]
> Currently, the bot is not in place at all (mainly because it doesn't support a limited voting period yet), so I'm counting votes manually instead. I intend to finish the work on the bot eventually, but probably not for this year's rulebook.

Ah, alright, I see. I thought it was done already.

> While it removes some clutter, it makes it less obvious where the votes come from. I think it would be simpler if you still commented with "+1" to make it obvious.

I can see what you mean and I agree. I just don't like the useless +1 comments, they are kind of frowned upon these days, though they are used in a different context here. There could be two alternatives to avoid them:
- Have someone post a comment "/voting starts" and then use comment reactions to have thumbs-up or thumbs-down, have the bot count that. Bot would sets the "vote-in-progress" label to indicate it's counting.
- Make voting an external web service and add it as a check. If an issue has a "vote-required" label, it will block until timeout and then is successful or not depending on outcome. In a perfect world, this "external webservice" could be as simple as displaying the interface as a check, the details link in check status leads there. Since you need to have a web service anyway to react to hooks, that would mean virtually zero overhead (no nice-to-read name required).

> Yes, I will take this into account when manually checking the results, and the bot will do that, too.

Alright.

**Comment by morxa** [comment]
> I can see what you mean and I agree. I just don't like the useless +1 comments, they are kind of frowned upon these days, though they are used in a different context here. There could be two alternatives to avoid them:
> 
>     * Have someone post a comment "/voting starts" and then use comment reactions to have thumbs-up or thumbs-down, have the bot count that. Bot would sets the "vote-in-progress" label to indicate it's counting.

For the first part, that's how the bot would work. I like the second idea with using thumbs-up and thumbs-down as votes, I filed it at morxa/votebot#8.
> 
>     * Make voting an external web service and add it as a check. If an issue has a "vote-required" label, it will block until timeout and then is successful or not depending on outcome. In a perfect world, this "external webservice" could be as simple as displaying the interface as a check, the details link in check status leads there. Since you need to have a web service anyway to react to hooks, that would mean virtually zero overhead (no nice-to-read name required).

Yes, blocking as a check would be nice. Do you mean that voting should also happen in the external webservice? That would require some additional work for authentication.

**Comment by timn** [comment]
> For the first part, that's how the bot would work. I like the second idea with using thumbs-up and thumbs-down as votes, I filed it at [morxa/votebot#8](https://github.com/morxa/votebot/issues/8).

Thanks, I'd like that :smile:.

> Yes, blocking as a check would be nice. Do you mean that voting should also happen in the external webservice? That would require some additional work for authentication.

Yes, it would probably require authenticating through Github. However, with the :+1:-:-1: solution mentioned above, it may simply count votes on updates (I guess there is a hook for such reactions?) and displaying them appropriately and passing/failing the check based on quorum (however that would be defined) or timeout and majority. There would be no need for authentication since the voting procedure is not moved into the check, only the counting. The detailed check status could at the end list the votes more clearly.
