### ISSUE TITLE
Make Exploration phase scoring more competitive

### ISSUE THREAD

**Issue by lyndwyrm666** [robocup-logistics/rcll-rulebook#36]
Comparing the maximum of 14 points which can be gained during exploration to the amount of points during production, it might make sense to create a bigger incentive to score during exploration.
Points that I could think of from the top of my head:

- Combo Score (multiply score with machines found)
- Multiplier with regards to time (Z stations found in X minutes gives Y multiplier)
- Competitive Multiplier (whoever finds CS1, CS2, etc..... first gains extra points)

Might be interesting to discuss.

Original Idea by Stefan Schiffer

**Comment by morxa** [comment]
The max number of points in the exploration phase was deliberatetily reduced to focus the game on the production. The initial plan was to actually get rid of the exploration phase eventually as soon as scoring in the game is not a big obstacle anymore.

We may want to adapt the scoring scheme, but the max number of points should not be increased, to keep the focus on production.

**Comment by lyndwyrm666** [comment]
ah, makes sense then.
