### ISSUE TITLE
Full Storage Station Integration Details

### ISSUE THREAD

**Issue by TarikViehmann** [robocup-logistics/rcll-rulebook#39]
As discussed in the last TC meeting, here is an issue where we can discuss the details for the payments made at the storage station.
Most work on the refbox to control the storage station is now done, for the full thing check out: https://github.com/robocup-logistics/rcll-refbox/pull/91.
To wrap up: All  48 shelf slots are usable, the refbox manages possiblly blocked slots, there are 6 pre-stored C0 products, one for each configuration, each on a different shelf. We still have to specify the associated costs for operations.

To quote the PR of the refbox repo:

There are 4 dfferent types of costs:
  - each retrieval, relocation and storage has some costs attached
  - each stored products induces costs each minute

Costs can be limited as follows:
  - The accumulated costs from all the four sources can be capped
  - the cost per minute can be capped to a max number of payments
  - A grace period for free storage time for each stored product can be used

We already agreed on making the usage costs small to begin with, so we can certainly disable some of these costs/functions if we like.
Goal of this Issue is to come up with values for:
 1. retrieveal costs
 2. storage costs
 3. relocation costs
 4. store-per-volume-per-minute costs
 5. grace-period time of free time before costs per minute starts (per product)
 6. max cost per minute per product
 7. max accumulated costs

8. Also we should decide whether pre-stored products also produce costs over time or not or if something else applies.

**Comment by TarikViehmann** [comment]
I would could for example imagine something like:
1. 5
2. 5
3. 0
4. 1
5. 120 seconds
6. 5
7. 30
8. No costs for pre-stored-products per minute

This might be a bit "cheap" as it only costs 5 points to use the pre-stored C0 for the "quantity-requested >1" order, we could also do 1. 10 and 2. 0 to change that.

What do you think?

**Comment by lyndwyrm666** [comment]
I'd prefer something like this:
1. 2
2. 2
3. 6
4. 1
5. 120 seconds
6. 5
7. Total loss of points, but no negative points
8. same as tarik
