### ISSUE TITLE
Challenge review for 2021

### ISSUE THREAD

**Issue by lyndwyrm666** [robocup-logistics/rcll-rulebook#41]
https://github.com/robocup-logistics/rcll-rulebook/blob/c7269e3c14941fe15daf63cfcce9e54a72efd47e/challenges.tex#L114
5 x 5

https://github.com/robocup-logistics/rcll-rulebook/blob/c7269e3c14941fe15daf63cfcce9e54a72efd47e/challenges.tex#L134
require

https://github.com/robocup-logistics/rcll-rulebook/blob/c7269e3c14941fe15daf63cfcce9e54a72efd47e/challenges.tex#L136
does

https://github.com/robocup-logistics/rcll-rulebook/blob/c7269e3c14941fe15daf63cfcce9e54a72efd47e/challenges.tex#L163
can be done while executing machine task

https://github.com/robocup-logistics/rcll-rulebook/blob/c7269e3c14941fe15daf63cfcce9e54a72efd47e/challenges.tex#L164
same as usual (two people take robot to insertion zone)

https://github.com/robocup-logistics/rcll-rulebook/blob/c7269e3c14941fe15daf63cfcce9e54a72efd47e/challenges.tex#L169
hardest difficulty

https://github.com/robocup-logistics/rcll-rulebook/blob/c7269e3c14941fe15daf63cfcce9e54a72efd47e/challenges.tex#L248
orders placed by webshop

https://github.com/robocup-logistics/rcll-rulebook/blob/c7269e3c14941fe15daf63cfcce9e54a72efd47e/challenges.tex#L266
unlabeled, but sorted by machines

**Comment by TarikViehmann** [comment]
Line 163 in c7269e3
 `\todo{replenisher not necessary for challenges?} `

This todo aims to question whether we even need a replenisher. We could also just limit the challenges themselves with only 3 capcarriers and 2 bases (one at each BS side) for example.

All your smaller remarks are now addressed in https://github.com/robocup-logistics/rcll-rulebook/commit/e9c11789c106284aa621be65f0cbc95080fa561a
