### ISSUE TITLE
Simplify Superfluous Rules

### ISSUE THREAD

**Issue by TarikViehmann** [robocup-logistics/rcll-rulebook#44]
There are currently quite a few rules in place that could be removed without changing the game in any way:
1. The Primary field halve
There is currently the notation of a "primary" halve where most machines of a particular team are located. We could remove that and resort to full randomness
2. Ring color randomization
Randomizing both ring colors and their costs is unecessary. For easier setup we could leave the ring colors constant and only randomize the color costs.
3. Storage station initial fillment
Pre-Buffered C0 do not need to be randomized. It proves nothing other than that teams can read protobuf messages and its quite a headache to fill the storage stations at the start of each game

**Comment by teamsolidus** [comment]
1) In a first phase it is easier if the machines are on each side, to avoid collisions. But in a further round of the tournament, may be we could switch to full random.
2) fully agree
3) fully agree

**Comment by wadaru** [comment]
1. if we use fully random placements, there is possibility that all MPS for one team are placed at one side. I think it is not good placement. For avoiding this problem, the number of switched MPSs should be  from two to five. And RefBox selects its number at randomly.
2. fully agree
3. fully agree
Thanks!
