### ISSUE TITLE
AR-Tags Library

### ISSUE THREAD

**Issue by teamsolidus** [robocup-logistics/rcll-rulebook#49]
Because the Alvar tags have been deprecated, i would like to propose that we switch to the Aruco tags, which are very common and more reliable.
Christian Deppe has confirmed to me that Festo is using the Aruco library in their Frameworks (RoboView, Smartsoft). So we also have a didactic consistency.

**Comment by TarikViehmann** [comment]
Sure, i am all in for it. Can you make the proposed changes and create a pull request for it? If you need assistance with it, let me know!

**Comment by pkohout** [comment]
good idea.

**Comment by TarikViehmann** [comment]
Closed in favor of https://github.com/robocup-logistics/rcll-rulebook/pull/52.
