### ISSUE TITLE
Robot extensions

### ISSUE THREAD

**Issue by morxa** [robocup-logistics/rcll-rulebook#6]
In TC meeting 2/19, it was proposed that a robot may extend beyond the limits during machine interaction. Extending beyond the usual limits is only allowed in the direction of the MPS.

The proposal should describe
* in what situations the robot may extend beyond the usual limits
* what the limits are in those situations (if any)
* in what direction it may extend

**Comment by teamsolidus** [comment]
In the rest position and while driving it also mustbe within the same diameter of the other additional hardware.
During interaction with a machine, the gripper may be extended to twice the robot diameter, provided that the direction is within the angle of the two outermost points of the corresponting MPS.
(i will push it later, fighting with windows git ;-))
