### ISSUE TITLE
Network description

### ISSUE THREAD

**Issue by pkohout** [robocup-logistics/rcll-rulebook#60]
Hi,

during the event in Aachen we had this network hickup, should we add a section Network at competition? Were we mention the IP of the refbox and the IP ranges that teams can use? Maybe even write which team uses which right now (GRIPS 105, Carologistics: 108, Solidus: 107). What do you think?

**Comment by wadaru** [comment]
On the previous competitions, we used IP number corresponding the table number, after that, they used the same IP number.
I think the IP ranges should be decided for each competition.
However, for convenience, we can use the fixed IP range. And this can avoid the number conflict.
BabyTigers would like to use 106.

**Comment by snoato** [comment]
We will expand on this in the rulebook but concrete decisions and assignments should be decided locally at the beginning of the event to be adaptive enough for changing circumstances.
