### ISSUE TITLE
Challenge track reservation

### ISSUE THREAD

**Issue by pkohout** [robocup-logistics/rcll-rulebook#79]
On the day where challenges are played, the reservation for playing slots should be clarified more. Theoretically it is possible that 2 teams use the playing field at the same time, bunt only one of them can access the refbox PC. We should make an update to the rules that the refbox PC has to be reserved also. Then a second team can use one halfe of the field for testing.

**Comment by snoato** [comment]
Is this issue urgent for the current season or can we defer the corresponding rule change for later?

**Comment by pkohout** [comment]
I don't think this is urgent for the current season. It also worked in Bangkok, only problem was that sometimes multiple teams wanted to use the refbox PC. But this year we know that this can happen :D

**Comment by snoato** [comment]
We will publish procedural and referee guidelines for events, competitions, and games following German Open 2024.
