### ISSUE TITLE
Storage Station

### ISSUE THREAD

**Issue by morxa** [robocup-logistics/rcll-rulebook#8]
As discussed several times, and in particular in meeting 2/19, we want to use the Storage Station in 2019.

The proposal was:
* the SS will have one copy of each possible C0 in storage
* a team can get a C0 for the price of 10 points from the SS
* each team can put the C0s in any order they want, which should be done by the replenisher before the game
* a robot has to request a `RETRIEVAL` and specify the storage position where to fetch the product from
* `STORE` requests will be ignored

**Comment by morxa** [comment]
Parts of the storage station usage are already in the rulebook but have not been implemented. We may still need to adapt the rules to reflect the latest proposal.

**Comment by dka14** [comment]
I agree that we should adapt the text in the rulebook following above proposal.

**Comment by morxa** [comment]
I've removed this from this year's milestone as the hardware will most probably not be ready for this year, as discussed in TC meeting 5/19.

**Comment by morxa** [comment]
See #39 and #40.
