### ISSUE TITLE
Navigation Challenge unclear

### ISSUE THREAD

**Issue by pkohout** [robocup-logistics/rcll-rulebook#94]
Mitzi thought that you have to send special messages to the refbox once you visit a zone. We should maybe add explanations which messages must be send in which challenge or so? I guess this will also come up with the grasping challenge next. This issue is more a reminder than something we have to act very soon on.

**Comment by snoato** [comment]
That's a fair point. It might be even more useful to provide a "Beginner's Guide to Challenges" though. Maybe something we can think about.

**Comment by snoato** [comment]
We will add documentation for this to the refbox repo.
