### ISSUE TITLE
Field Test

### ISSUE THREAD

**Issue by pkohout** [robocup-logistics/rcll-rulebook#95]
Hi,

since we had today the problem that the Magenta machines did not work, maybe in future events we should plan a timeslot where we let the refbox communicate with all machines (prepare them) to check if they all work? I could write a simple UI tool to send the prepares so that this can easily be done, and we "play" a game where humans carry the bases to the machines, in order to check if they operate as expected.

what do you guys think about this?

**Comment by snoato** [comment]
Do you still want to do this? Since this is just a procedural change I don't think it would be necessary to include it in the rulebook.

**Comment by snoato** [comment]
We will publish procedural and referee guidelines for events, competitions, and games following German Open 2024.
